### ISSUE TITLE
suggestion: exe version

### ISSUE THREAD

**Issue by furllmm** [openrecall/openrecall#58] opened 2024-06-17 08:40 UTC
title

**Comment by Nox13last** [comment] 2024-06-17 17:46
Make a .BAT.
```
@echo off
title OpenRecall Updater
pip install --upgrade --no-cache-dir git+https://github.com/openrecall/openrecall.git
title OpenRecall
cls
python3 -m openrecall.app
```

**Comment by furllmm** [comment] 2024-06-18 11:00
ty 
where is data path

**Comment by Nox13last** [comment] 2024-06-18 23:40
You mean where the database is and where the screenshots are kept?
That's `%AppData%\openrecall\`  (or `C:\Users\[Your Username]\AppData\Roaming\openrecall`)

**Comment by koenvaneijk** [comment] 2024-06-19 17:16
This is on our roadmap! Closing this as it is a duplicate of #22

**Closed by koenvaneijk** 2024-06-19 17:16 UTC
